version: '3.9' 

services:
  db: 
    image: postgres:16
    container_name: db 
    environment:
      POSTGRES_DB: operator_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - ms-operator 
  
  ms-operator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-operator
    env_file:
      - .env
    ports:
      - "3000:3000" 
    depends_on:
      - db 
    networks:
      - ms-operator


networks:
  ms-operator: