spring:
  application:
    name: ${SERVER_NAME}

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true 
    hibernate:
      ddl-auto: update 
    properties:
      hibernate:
        format-sql: true 
    defer-datasource-initialization: true
  
  sql: 
    init: 
     mode: always

server:
  port: ${SERVER_PORT}
  service-url: ${SEARCH_SERVER}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    preferIpAddress: true
    hostname: ${SERVER_NAME}

springdoc:
  api-docs:
    enabled: true 
  swagger-ui: 
    enabled: true